In [2]:
import pandas as pd

In [4]:
df = pd.read_pickle("data_sources/fused/accident_weather.pkl")
df.head(12)

,Vehicles.VehicleNumber,Vehicles.DamageLevel,Vehicles.ExplosionType,Vehicles.FireType,Vehicles.SerialNumber,Vehicles.Make,Vehicles.Model,Vehicles.NumberOfEngines,Vehicles.RegistrationNumber,Vehicles.FlightOperationType,...,wx_cloud_cover_high,wx_wind_speed_10m,wx_wind_speed_100m,wx_wind_direction_10m,wx_wind_direction_100m,wx_wind_gusts_10m,wx_weather_code,wx_snow_depth,wx_weather_day,wx_time_diff
0,1,substantial,none,none,0702,cirrus design corp,sr22t,1,n773gb,pers,...,0.0,22.6,31.5,326.0,327.0,39.6,71.0,0.02,2023-12-31,0 days 00:20:00
1,1,substantial,none,none,004ce,golden avio s r l,f30 brio,1,n37ga,pers,...,0.0,8.1,11.6,201.0,202.0,21.6,0.0,0.00,2023-12-31,0 days 00:13:00
2,1,substantial,none,none,4692139,piper aircraft inc,pa46r-350t,1,n539ma,pers,...,9.0,2.6,8.1,56.0,21.0,8.3,0.0,0.00,2023-12-31,0 days 00:13:00
3,1,substantial,none,none,79-30941,bellanca,17-30a,1,n678mj,pers,...,0.0,10.4,14.8,256.0,256.0,24.5,0.0,0.02,2023-12-30,0 days 00:00:00
4,1,substantial,none,none,7452c,maule,m-6-235,1,n71ms,aobv,...,0.0,11.0,14.5,302.0,305.0,23.0,0.0,0.00,2023-12-29,0 days 00:27:00
5,1,substantial,none,none,18-4403,piper,pa-18a 150,1,n2774p,pers,...,3.0,14.6,28.9,290.0,301.0,25.6,0.0,0.09,2023-12-29,0 days 00:00:00
6,1,substantial,none,none,1127,progressive aerodyne inc,searey lsa,1,n312pr,pers,...,23.0,8.4,2.9,263.0,330.0,9.4,1.0,0.00,2023-12-28,0 days 00:03:00
7,1,substantial,none,none,2939,cirrus design corp,sr22,1,n858rc,pers,...,0.0,16.2,21.7,193.0,192.0,31.7,0.0,0.00,2023-12-26,0 days 00:13:00
8,1,substantial,none,none,34-7970268,piper,pa-34-200t,2,n510p,pers,...,14.0,19.4,33.4,230.0,235.0,33.1,3.0,0.00,2023-12-26,0 days 00:15:00
9,1,substantial,none,none,21061930,cessna,210m,1,n6pd,pers,...,99.0,17.5,25.5,104.0,103.0,34.9,3.0,0.00,2023-12-23,0 days 00:30:00
10,1,substantial,none,none,17274808,cessna,172p,1,n53725,pers,...,85.0,20.0,32.2,67.0,65.0,37.1,3.0,0.00,2023-12-23,0 days 00:00:00
11,1,substantial,none,none,7074,taylorcraft,bc12-d,1,n43415,pers,...,0.0,9.7,17.8,132.0,162.0,26.3,3.0,0.07,2023-12-23,0 days 00:25:00

In [ ]:
df = pd.read_pickle("data_sources/filtered/airline.pkl")
df.head(12)

In [9]:
df = pd.read_pickle("data_sources/filtered/ntsb.pkl")
df["HighestInjury"]

0           none
1           none
2          fatal
3        serious
4           none
          ...
23398       none
23399       none
23400      fatal
23401    serious
23402      fatal
Name: HighestInjury, Length: 23403, dtype: category
Categories (4, object): ['fatal', 'minor', 'none', 'serious']

In [3]:
df = pd.read_pickle("data_sources/filtered/airline.pkl")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Year     249 non-null    int32
 1   Month    249 non-null    int32
 2   Dom_Pax  249 non-null    int32
 3   Int_Pax  249 non-null    int32
 4   Pax      249 non-null    int32
 5   Dom_Flt  249 non-null    int32
 6   Int_Flt  249 non-null    int32
 7   Flt      249 non-null    int32
 8   Dom_LF   249 non-null    int32
 9   Int_LF   249 non-null    int32
 10  LF       249 non-null    int32
dtypes: int32(11)
memory usage: 10.8 KB