In [2]:
import pandas as pd

In [3]:
df = pd.read_pickle("data_sources/filtered/weather.pkl")
df.head(12)

,AccidentID,time,temperature_2m,relative_humidity_2m,dew_point_2m,pressure_msl,surface_pressure,precipitation,rain,snowfall,...,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed_10m,wind_speed_100m,wind_direction_10m,wind_direction_100m,wind_gusts_10m,weather_code,snow_depth
0,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 00:00:00,1.1,85,-1.1,1011.4,983.2,0.0,0.0,0.0,...,0,88,100,12.0,26.0,261,266,19.1,3,0.02
1,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 01:00:00,-0.6,89,-2.2,1012.5,984.0,0.0,0.0,0.0,...,46,0,76,11.2,25.5,272,279,19.1,3,0.02
2,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 02:00:00,-1.0,89,-2.6,1012.8,984.3,0.0,0.0,0.0,...,100,0,0,13.2,27.7,292,300,21.2,3,0.02
3,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 03:00:00,-0.4,80,-3.5,1013.3,984.8,0.0,0.0,0.0,...,100,0,0,16.6,27.6,319,320,26.6,3,0.02
4,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 04:00:00,-1.3,71,-5.8,1013.5,984.9,0.0,0.0,0.0,...,100,0,0,17.4,27.5,310,312,29.2,3,0.02
5,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 05:00:00,-1.8,69,-6.7,1013.9,985.3,0.0,0.0,0.0,...,100,0,0,16.7,26.1,303,305,28.8,3,0.02
6,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 06:00:00,-2.2,70,-6.8,1014.2,985.5,0.0,0.0,0.0,...,100,0,0,15.8,25.6,297,299,28.1,3,0.02
7,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 07:00:00,-2.7,74,-6.7,1014.0,985.3,0.0,0.0,0.0,...,100,25,0,16.7,27.9,284,287,27.4,3,0.02
8,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 08:00:00,-2.7,73,-6.9,1014.1,985.4,0.0,0.0,0.0,...,100,12,0,17.8,28.5,288,291,29.9,3,0.02
9,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 09:00:00,-2.9,71,-7.4,1014.6,985.9,0.0,0.0,0.0,...,100,37,0,18.1,28.7,293,297,30.2,3,0.02
10,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 10:00:00,-3.2,72,-7.5,1014.6,985.8,0.0,0.0,0.0,...,100,45,0,18.5,29.3,294,298,31.0,3,0.02
11,cen24la079_2023-12-31_41.610278_-90.588361,2023-12-31 11:00:00,-3.1,76,-6.8,1014.8,986.0,0.0,0.0,0.0,...,100,98,0,17.7,27.5,294,297,31.7,3,0.02

In [ ]:
df = pd.read_pickle("data_sources/filtered/airline.pkl")
df.head(12)

In [9]:
df = pd.read_pickle("data_sources/filtered/ntsb.pkl")
df["HighestInjury"]

0           none
1           none
2          fatal
3        serious
4           none
          ...
23398       none
23399       none
23400      fatal
23401    serious
23402      fatal
Name: HighestInjury, Length: 23403, dtype: category
Categories (4, object): ['fatal', 'minor', 'none', 'serious']